require("core.options")
require("core.keymaps")
require("core.lazy")

require("config.mason")
require("config.lsp")
require("config.cmp")
require("config.treesitter")
require("config.treesitter-context")
require("config.telescope")
require("config.conform")
require("config.nvim-lint")
require("config.copilot")
require("config.comment")
require("config.diffview")
require("config.which-key")
require("config.nvim-tree")
require("config.gitsigns")
